version: "3.1"

services:
  postgresql:
    image: postgres
    container_name: pokeapp_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pokeapp_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - postgresql

  frontend:
    build:
      context: ./frontend/vue_pokeapp
      dockerfile: Dockerfile
    container_name: pokeapp_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/vue_pokeapp:/app
    working_dir: /app
    depends_on:
      - backend

volumes:
  postgres_data:
    