"""add users table

Revision ID: c65941bbd2e1
Revises: 
Create Date: 2024-08-31 13:54:49.020325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65941bbd2e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_users_id'), 'tb_users', ['id'], unique=False)
    op.create_index(op.f('ix_tb_users_username'), 'tb_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_users_username'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_id'), table_name='tb_users')
    op.drop_table('tb_users')
    # ### end Alembic commands ###
